<h4> <?php echo $this->info; ?> </h4>

<table>
 <tr>
  <th> ISBN <th>
  <th> Autor <th>
  <th> Tytul <th>
  <th> Cena <th>
  <th> Akcja <th>
 <tr>
 <?php foreach($this->rows as $intIndex => $arrRow): ?>
 <tr>
  <td><?php echo $arrRow['isbn']; ?><td>
  <td><?php echo $arrRow['autor']; ?><td>
  <td><?php echo $arrRow['tytul']; ?><td>
  <td><?php echo $arrRow['cena']; ?><td>
  <td> 
   <a href="http://zf2.loc/application/ksiazka/edytuj?isbn=<?php echo $arrRow['isbn'];?>">Edytuj</a>
   <a href="http://zf2.loc/application/ksiazka/usun?isbn=<?php echo $arrRow['isbn'];?>">Usuń</a> 
  </td>
 <tr>
 <?php endforeach; ?>
</table>