<?php
$title = 'Add new ksiazka';
 $this->headTitle($title);
 
 echo $this->url('ksiegarnia', array('action' => 'wstaw'));
 echo $this->url('application', array('controller'=> 'index', 'action' => 'index'));
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 //$form->setAttribute('action', $this->url('ksiazka', array('action' => 'add')));
 $form->prepare();
 
 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('title'));
 echo $this->formRow($form->get('artist'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();